name: Python unit tests

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [  "3.9" ]

    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          channels: conda-forge, defaults
          use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!
          auto-update-conda: true
          auto-activate-base: true
          show-channel-urls: true
          channel-priority: true
          allow-softlinks: true
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          conda activate test
          conda search -vv sphinx-rtd-theme
          wget https://conda.anaconda.org/conda-forge/noarch/repodata.json
          grep sphinx-rtd-theme repodata.json
